sudo: required

language: javascript

services:
  - docker

script:
  - docker build -t jpodeszwik/weight-tracker .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push jpodeszwik/weight-tracker

